{{- if .Values.conf.loki.enabled }}
{{- if and (.Values.conf.loki.password) (.Values.conf.loki.passwordSecret) }}
{{ fail "Both of loki.password and loki.passwordSecret could not be provided! Please choose only one of them." }}
{{- end }}

{{- if and (or .Values.conf.loki.username .Values.conf.loki.password) (not .Values.conf.loki.passwordSecret) }}
{{ $currentScope := .}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "fluentd-kube-elastic.loki-secret" . }}
  labels:
    {{- include "fluentd-kube-elastic.labels" . | nindent 4 }}
data:
  {{- if .Values.conf.loki.username }}
  LOKI_USERNAME: {{ .Values.conf.loki.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.conf.loki.password }}
  LOKI_PASSWORD: {{ .Values.conf.loki.password | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
